version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_mc3zRWHGX2ph@ep-sparkling-glitter-ade65204-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_SECRET=mini_bharat_ai_store_secret_key
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:3001/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge